docs/verify.md
Enhance the doc.
Enhance the doc.
tested
=> fix: update the verify doc to be more accurate

COPYING-KEYSTONE
update license
update license file
No need
=> update the license

docs/verify.md
Update link
Update link
No need test
=> doc: Update links on verify.md

src/ui/gui_widgets/gui_key_derivation_request_widgets.c
Fix an ADA memory crash after code refactor.
correct the value used.
=> fix(debugmemory): ada memory crash

src/driver/drv_aw32001.c, src/driver/drv_battery.c, src/driver/hardware_version.c, src/driver/hardware_version.h, src/managers/fingerprint_process.c
adapt hardware v3.2
1. update fingerprint ldo work
2. update battery voltage get
3. update version 3.2
=> adapt hardware v3.2

src/driver/drv_aw32001.c, src/driver/drv_battery.c, src/driver/hardware_version.c, src/driver/hardware_version.h, src/managers/fingerprint_process.c
Reverts KeystoneHQ/keystone3-firmware#387
=> Revert "adapt hardware v3.2"

src/driver/drv_battery.c, src/driver/hardware_version.c, src/driver/hardware_version.h, src/ui/gui_views/gui_init_view.c
=> revert v3.2 code

src/managers/fingerprint_process.c, src/managers/fingerprint_process.h, src/ui/gui_widgets/gui_about_info_widgets.c
update fingerprint 
add fp chip id status
no need to test
=> fix:fp status

src/ui/gui_components/gui_page.c, src/ui/gui_frame/gui.h, src/ui/gui_frame/gui_framework.c, src/ui/gui_widgets/gui_scan_widgets.c
=> fix:add content zone delete

src/driver/drv_power.c, src/driver/drv_power.h
jira:PRAD-3968  
Firmware external dependency grooming
delete bluetooth power
no neeed to test
=> fix:delete bluetooth power

src/managers/fingerprint_process.c
adapt fingerprint 
enable fingprint module ldo
no need to test
=> adapt fingprint

src/ui/gui_widgets/gui_forget_pass_widgets.c, src/ui/gui_widgets/gui_forget_pass_widgets.h, src/ui/gui_widgets/gui_lock_widgets.c
jira:PRAD-3991
fix pass passphrase wallet forget passwrod scene
Enter the home screen after forgetting the password from the passphrase wallet
Enter the pass phrase wallet and execute the forgot password process
=> go home when passphrase forget password

src/ui/wallet/gui_wallet.c
Connect OKX with TRX,LTC,DASH,BCH.
Connect OKX.
Connect OKX.
=> fix: connect OKX with TRX,LTC,DASH,BCH

src/ui/gui_widgets/gui_web_auth_result_widgets.c, src/ui/gui_widgets/gui_web_auth_result_widgets.h
This PR fixes oom issue on web auth case.
Fix the bug caused by code refactor
Try web auth again.
=> fix: rust out of memory on web auth

.github/PULL_REQUEST_TEMPLATE.MD
=> doc: update github PR template

src/crypto/secret_cache.c
This PR fixes an existing bug of slip39 generation
=> fix(slip39): index exceeded

src/ui/gui_model/gui_model.c
This PR adds entropy duplication check when adding new entropy.
=> fix(dice-rolls): check entropy duplication

src/ui/gui_widgets/gui_dice_rolls_widgets.c
=> fix(dice-rolls): ui issues

src/driver/power_on_self_check.c, src/main.c, src/managers/account_manager.c, src/managers/account_manager.h
jira：PRAD-3928
wipe device after reaching the specified number of times
input error passcode reach times
=> when loginPasswordErrorCount Reach the set number of times

src/ui/gui_chain/gui_cosmos.c
Reboot when parse cosmos tx.
Cosmos tx of borrow.
=> fix: parse cosmos tx

src/ui/gui_widgets/gui_standard_receive_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c
Hide button of more with LTC,BCH,DASH,TRX.
Receive page of LTC,BCH,DASH,TRX.
=> fix: no btn of more with LTC,BCH,DASH,TRX

src/ui/gui_widgets/gui_dice_rolls_widgets.c, src/ui/lv_i18n/lv_i18n.c
This PR fixes dice roll ui issues.
=> Fix dice rolls

src/ui/lv_i18n/lv_i18n.c
This PR update dice-rolls text.
=> feat(dice-rolls): update text

src/ui/gui_frame/gui_framework.c, src/ui/gui_frame/gui_framework.h, test/test_cmd.c
jira:prad-4031
debug gui view open and close
no need
=> add ui cmd

src/ui/lv_i18n/lv_i18n.c
Update text of checksum desc.
The page of checksum.
=> fix: update text of checksum desc

src/ui/gui_chain/gui_trx.c
Sign TRX with SLIP39.
Send TRX in OKX.
=> fix: sign TRX

src/ui/lv_i18n/lv_i18n.c
Update text.
Verify Source Code.
=> fix: update text

src/ui/gui_components/gui_status_bar.c, src/ui/gui_widgets/gui_dice_rolls_widgets.c
=> fix(dice-rolls): update ui

src/ui/gui_widgets/gui_dice_rolls_widgets.c
=> fix(dice-rolls): ui issue

src/ui/gui_model/gui_model.c
=> clear api error

src/ui/gui_chain/gui_eth.c
Fix parsing eth contract.
Sign ETH.
=> fix: parse eth contract

src/driver/low_power.c, src/driver/usb/usbd_composite.c, src/tasks/qrdecode_task.c, src/tasks/usb_task.c, src/tasks/usb_task.h, src/ui/gui_views/gui_init_view.c, src/ui/gui_widgets/gui_dice_rolls_widgets.c, src/ui/gui_widgets/gui_lock_widgets.c, src/ui/gui_widgets/gui_usb_connection_widgets.c, src/ui/lv_i18n/lv_i18n.c, src/user_sqlite3.c, src/webusb_protocol/eapdu_protocol_parser.c, src/webusb_protocol/eapdu_services/service_echo_test.c, src/webusb_protocol/eapdu_services/service_export_address.c, src/webusb_protocol/eapdu_services/service_resolve_ur.c, src/webusb_protocol/internal_protocol_parser.c, src/webusb_protocol/protocol_parse.c
1.usb initial optimization 
2.buffer edge check
no need
=> code optimization

src/ui/gui_widgets/gui_connect_wallet_widgets.c
Add coin icons of OKX.
Connect OKX
=> fix: add coin icons of OKX

external/mh1903_lib/SCPU_USB_Lib/SCPU_USB_Device_Library/Core/src/usbd_core.c, src/driver/low_power.c, src/driver/usb/drv_usb.c, src/tasks/background_task.c, src/ui/gui_views/gui_init_view.c, src/ui/gui_widgets/gui_lock_widgets.c
fix usb insert ui issues
usb insert scene
=> usb status bug fix

src/driver/low_power.c, src/tasks/fingerprint_task.c
Fix a heap leak.
Lock then unlock repeatly, view heap memory remaining information.
=> Remove unnecessary timer creation.

external/mh1903_lib/SCPU_USB_Lib/SCPU_USB_Device_Library/Core/src/usbd_core.c, src/driver/low_power.c, src/driver/usb/drv_usb.c, src/tasks/usb_task.c, src/ui/gui_views/gui_init_view.c, src/ui/gui_widgets/gui_connection_widgets.c, src/ui/gui_widgets/gui_setup_widgets.c, src/ui/gui_widgets/gui_setup_widgets.h
setup view window pop up when usb insert
setup usb init
=> setup view add usb init

src/managers/fingerprint_process.c, src/tasks/fingerprint_task.c, ui_simulator/LVGL.Simulator/main.c
finger print recognize timer init
fp unlock device
=> finger print recognize

external/mh1903_lib/SCPU_USB_Lib/SCPU_USB_Device_Library/Core/src/usbd_core.c, src/driver/low_power.c, src/driver/usb/drv_usb.c, src/tasks/usb_task.c, src/ui/gui_views/gui_init_view.c
1. wakeup bug
2. setup view error
jira:prad-4094
=> device wakeup error

external/mh1903_lib/SCPU_USB_Lib/SCPU_USB_Device_Library/Core/src/usbd_core.c, src/driver/usb/drv_usb.c, src/tasks/usb_task.c, src/ui/gui_widgets/gui_lock_widgets.c
usb connect window pop up when unlock device
check unlock device status
=> usb connect window pop up when unlock device

src/ui/gui_widgets/gui_connect_wallet_widgets.c, src/ui/gui_widgets/gui_multi_accounts_receive_widgets.c, src/ui/gui_widgets/gui_multi_path_coin_receive_widgets.c, src/ui/gui_widgets/gui_select_address_widgets.c, src/ui/gui_widgets/gui_standard_receive_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c, ui_mac_simulator/assets/home_coins.json
Feature: add confirm button.
1. Receive coin.
2. Connect wallet.
=> Feature: add confirm button

rust/apps/cosmos/src/proto_wrapper/msg/msg.rs
Fix: parse cosmos IBC tx.
Sign cosmos tx.
=> Fix: parse cosmos IBC tx

rust/rust_c/src/bitcoin/src/address.rs, src/ui/gui_views/gui_init_view.c, src/ui/gui_widgets/gui_connection_widgets.c, src/ui/gui_widgets/gui_export_pubkey_widgets.c, ui_mac_simulator/src/lib/simulator_model.c, ui_mac_simulator/src/lib/simulator_model.h
Feat: convert version of xpub.
Export xpub of BTC.
=> Feat: convert version of xpub

src/ui/gui_widgets/gui_multi_path_coin_receive_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c
Fix: update address when switch type.
Switch address type of BTC,ETH,SOL.
=> fix: update address when switch type

src/ui/gui_widgets/gui_multi_path_coin_receive_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c
Not set selected index when deinit selecting address page of BTC,ETH.
Lock screen when select address.
=> fix: not set selected index when deinit

src/webusb_protocol/internal_protocol_parser.c
=> fix usb buffer edge check

src/driver/low_power.c, src/ui/gui_components/gui_status_bar.c
Implement dynamic status bar layout. Fix some status bar bugs.
Insert the USB cable and SD card.
=> Implement dynamic status bar layout. Fix some status bar bugs.

src/driver/low_power.c
Fix status bar issue.
Insert/Remove USB cable and SD card.
=> Fix status bar issue.

src/tasks/background_task.c, src/tasks/usb_task.c
=> revert usb waketup

src/driver/low_power.c, src/driver/usb/drv_usb.c, src/driver/usb/drv_usb.h, src/tasks/usb_task.c, src/ui/gui_model/gui_model.c, src/ui/gui_widgets/gui_usb_connection_widgets.c
1. setup view usb window
2. delete wallet usb deinit
jira:PRAD-4119
=> fix delete wallet bug

src/driver/low_power.c, src/managers/screen_manager.c
forget password scene wakeup
jira:PRAD-4118
=> wakeup bug

src/tasks/background_task.c
Timeout for reboot and power off option.
=> Timeout for reboot and power off option.

src/tasks/background_app.c, src/tasks/background_task.c
Disable all hardware when power off with USB plugged in.
Power off with USB plugged in.
=> Disable all hardware when power off with USB plugged in.

src/ui/gui_components/gui_keyboard_hintbox.c
=> Fix clear data macro.

src/device_settings.c
=> update default air gap status

tools/log_analyzer/.gitignore, tools/log_analyzer/event log table.csv, tools/log_analyzer/log_analyzer.py
Log analyzer tool.
python log_analyzer.py [log_file_name]
=> Log analyzer tool.

src/driver/drv_battery.c, src/driver/low_power.c
Lock kernel during AD conversion.
=> Lock kernel during AD conversion.

src/ui/gui_widgets/gui_update_success_widgets.c
add update success view clickable
check update success view
=> add update success view clickable

rust/apps/sui/Cargo.lock, rust/apps/sui/Cargo.toml, rust/rust_c/Cargo.lock, rust/rust_c/Cargo.toml, rust/rust_c/src/lib.rs, rust/rust_c/src/sui/Cargo.toml, ui_mac_simulator/platformio.ini, ui_mac_simulator/src/lib/rust/librust_c.a, ui_mac_simulator/src/lib/simulator_model.c, ui_mac_simulator/src/lib/simulator_model.h, ui_mac_simulator/src/main.c
THIS PR supports rust static library on simulator.
=> Support simulator rust

src/ui/gui_components/gui_keyboard_hintbox.c
close usb when error password up to limit times
=> close usb when error password up to limit times

CMakeLists.txt, src/tasks/cmd_task.c, test/test_cmd.c
=> Enable test cmd for btc_only.

src/ui/gui_components/gui_keyboard_hintbox.c
fix lock device view disable usb coin
=> fix lock device view disable usb coin

src/main.c, src/managers/account_manager.c, src/managers/account_manager.h
Accounts data check.
Force reboot the device when creating account.
=> Accounts data check.

src/ui/gui_widgets/btc_only/gui_home_widgets.c, src/ui/gui_widgets/general/gui_home_widgets.c
=> delete extra code

src/ui/gui_widgets/gui_pop_message_box.c
Do not call any msg box when anim running.
Long press the button when anim running.
=> Do not call any msg box when anim running.

src/ui/gui_views/gui_init_view.c, src/ui/gui_widgets/gui_lock_widgets.c, ui_simulator/LVGL.Simulator/LVGL.Simulator.vcxproj, ui_simulator/LVGL.Simulator/LVGL.Simulator.vcxproj.filters
=> Fix ui_simulator

rust/apps/bitcoin/src/addresses/address.rs, rust/apps/bitcoin/src/addresses/mod.rs, rust/apps/bitcoin/src/lib.rs
Feat: Support BTC testnet address.
Switch BTC network to testnet.
=> Support BTC testnet address

src/ui/gui_widgets/gui_export_pubkey_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c
Fixed display issue in address settings page items
=> Fix ui error

src/ui/gui_widgets/gui_export_pubkey_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c
Reverts KeystoneHQ/keystone3-firmware#558
=> Revert "Fix ui error"

src/ui/gui_widgets/gui_export_pubkey_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c
Fixed display issue in address settings page items
=> fix: [4205] btc address setting ui error

src/device_settings.c
Keep the original configuration when upgrading config
=> keep the original configuration when upgrading config

src/device_settings.c, src/ui/gui_widgets/gui_connection_widgets.c
=> air gap status update

src/driver/low_power.c, src/managers/screen_manager.c, src/tasks/usb_task.c, src/ui/gui_widgets/gui_usb_connection_widgets.c
remove unnecessary usb deinit.
=> fix:remove unnecessary usb deinit.

.gitignore, CMakeLists.txt, build.py, scripts/read_feature_toggle.py, src/config/feature_toggle.yaml
=> build: add feature_toggle config file

src/ui/gui_widgets/btc_only/gui_btc_wallet_profile_widgets.c
fix:set g_networkCont to NULL after lv_obj_del
=> fix:set g_networkCont to NULL after lv_obj_del

rust/apps/wallets/src/blue_wallet.rs, rust/rust_c/src/wallet/src/btc_only_wallet/src/lib.rs, src/ui/gui_widgets/gui_connect_wallet_widgets.c, src/ui/wallet/gui_wallet.c, src/ui/wallet/gui_wallet.h
export only segwit xpub to specter.
Connect wallet.
=> export only segwit xpub to specter.

src/ui/lv_i18n/lv_i18n.c
=> i18n update

src/ui/gui_widgets/gui_connect_wallet_widgets.c, src/ui/gui_widgets/gui_select_address_widgets.c
=> fix: address overflow

CHANGELOG-BTC.md
=> add changelog

src/ui/gui_components/gui_keyboard.c, src/ui/gui_components/gui_mnemonic_input.c, src/ui/gui_widgets/gui_enter_passcode.c
=> fix:Using macros incorrectly

CMakeLists.txt
=> fix device error reboot

rust/apps/wallets/src/blue_wallet.rs, src/ui/wallet/gui_wallet.c
fix:connect wallet with test net.
Switch to test net and then connect wallet.
=> fix:connect wallet with test net.

src/ui/gui_widgets/setting/gui_setting_widgets.c
=> fix:devcie setting title

src/ui/gui_widgets/gui_forget_pass_widgets.c
forget password deinit use null ptr
=> fix:use null ptr

src/ui/gui_widgets/gui_utxo_receive_widgets.c
=> fix:address buffer format

src/ui/gui_chain/others/gui_eth.c, src/ui/gui_widgets/gui_export_pubkey_widgets.c
=> fix eth abi error

src/ui/gui_widgets/gui_export_pubkey_widgets.c
=> fix:extended zpub,ypub

src/ui/gui_chain/others/gui_aptos.c, src/ui/gui_chain/others/gui_sui.c, src/ui/gui_chain/others/gui_xrp.c
fix xrp、aptos、sui buffer too long bug
=> fix xrp、aptos、sui buffer too long bug

src/ui/gui_widgets/gui_export_pubkey_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c
Swap address type. Set native-segwit address as default.
BTC receive page.
BTC export xpub page.
=> Swap address type. Set native-segwit address as default.

src/ui/gui_widgets/gui_utxo_receive_widgets.c
=> fix:dash recv view crash

rust/apps/ethereum/src/eip712/eip712.rs, rust/apps/ethereum/src/lib.rs
Resolve non-standard EIP712 tx parsing
```javascript
const verifyingContract: address | string;
const salt: bytes32 | string;
```
=> fix: resolve non-standard EIP712 tx parsing

src/ui/gui_components/gui_keyboard.c, src/ui/gui_components/gui_letter_tree.c
=> letter keyboard crash

rust/apps/cosmos/src/proto_wrapper/fee.rs
https://keystonejira.atlassian.net/browse/PRAD-4325
=> fix: precision issue with dym and inj

src/firmware/firmware_update.c
check SD card OTA file head.
1. copy a damaged ota file to sd card.
2. insert the sd card to device.
=> fix:check SD card OTA file head.

src/driver/drv_sdio.c
fix:return false immediately when Querying SDIO status, for avoiding stuck at the driver layer.
Remove SD card when upgrading firmware via SD card.
=> fix:return false immediately when Querying SDIO status, for avoiding stuck at the driver layer.

rust/apps/cardano/src/address.rs, rust/apps/cardano/src/structs.rs
This PR modify the checking logic when parsing an ADA transaction.
=> fix(cardano): only check payment keyhash when parsing ADA transactions

src/ui/gui_widgets/gui_lock_widgets.c, src/ui/gui_widgets/gui_passphrase_widgets.c
passphrase quick access goto home
=> fix:passphrase quick access goto home

external/fatfs/diskio.c, external/fatfs/ff.c, src/driver/drv_sdcard.c, src/driver/drv_sdcard.h, src/user_fatfs.c, src/user_fatfs.h, test/test_cmd.c
feature:sd card fat32 disk format.
test cmd.
=> feature:sd card fat32 disk format.

src/user_sqlite3.c
=> fix abi crash

src/driver/drv_qrdecode.c
fix:make sure DMA is done before copying next frame of camera data.
=> fix:make sure DMA is done before copying next frame of camera data.

src/driver/hardware_version.c
=> fix spell mistake

src/crypto/account_public_info.c, src/managers/account_manager.c, src/managers/keystore.c, src/managers/se_manager.c, src/ui/gui_model/gui_model.h, src/ui/gui_widgets/gui_export_pubkey_widgets.c, src/ui/gui_widgets/gui_firmware_update_widgets.c, src/ui/wallet/gui_qr_code.c, src/utils/user_utils.c, ui_simulator/simulator_mock_define.h
THIS PR fixes simulator build.
=> fix(simulator): fix build

src/ui/gui_model/gui_model.c
=> fix:passphrase relock assert

rust/apps/cardano/Cargo.lock, rust/apps/cardano/Cargo.toml, rust/rust_c/Cargo.lock
=> fix: improve memory usage to fix keystone OOM

external/cjson/cJSON.c, external/cjson/cJSON.h, src/ram/user_memory.c, src/ram/user_memory.h
=> update json version

src/ui/gui_widgets/gui_utxo_receive_widgets.c
=> fix address setting ui bug

rust/rust_c/CMakeLists.txt, rust/rust_c/Cargo.toml, rust/rust_c/features.cmake
=> chore: add rust features config

src/ui/gui_widgets/gui_export_pubkey_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c
=> fix: build

rust/apps/ethereum/src/eip712/eip712.rs, rust/apps/ethereum/src/eip712/serde_helpers.rs, rust/apps/ethereum/src/lib.rs
Encoding EIP712 salt is not right.
Withdraw in [helixapp.com](https://helixapp.com/).
=> Fix: encode EIP712 salt

CMakeLists.txt, src/ui/gui_model/gui_model.c, src/ui/gui_widgets/gui_import_phrase_widgets.c, src/ui/gui_widgets/gui_scan_widgets.c, src/ui/gui_widgets/gui_setup_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c, ui_simulator/simulator.cmake, ui_simulator/simulator_model.c, ui_simulator/simulator_model.h
=> fix(simulator): build

src/config/version_btc_only.h, src/ui/gui_widgets/gui_utxo_receive_widgets.c
=> Pick commits

src/ui/gui_widgets/gui_connection_widgets.c
fix:sdcard format when sdcard not insert
=> fix:sdcard format when sdcard not insert

CMakeLists.txt, src/ui/gui_frame/gui_framework.c, src/ui/gui_frame/gui_obj.h, src/ui/gui_views/gui_init_view.c, src/ui/gui_views/gui_views.h, src/ui/gui_views/multi_sig/gui_multi_sig_import_wallet_info_view.c, src/ui/gui_widgets/multi_sig/gui_multi_sig_import_wallet_info_widgets.c, src/ui/gui_widgets/multi_sig/gui_multi_sig_import_wallet_info_widgets.h, ui_simulator/simulator_model.c, ui_simulator/simulator_model.h
=> fix simulator add add multisig-info view

src/ui/gui_widgets/gui_connect_wallet_widgets.c
=> feat: hide specter

src/ui/gui_widgets/gui_utxo_receive_widgets.c
=> fix(btc_only): receive address error

src/crypto/account_public_info.c, src/ui/gui_widgets/gui_export_pubkey_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c, ui_simulator/simulator_model.c, ui_simulator/simulator_model.h
=> fix build and bugs

src/user_sqlite3.c
=> memory edge control

src/managers/fingerprint_process.c, src/managers/screen_manager.c
=> fix device sleep cant wake up

src/ui/gui_widgets/gui_global_resources.c, src/ui/gui_widgets/gui_global_resources.h, src/ui/lv_i18n/lv_i18n.c
=> fix taproot order

rust/apps/bitcoin/Cargo.lock, rust/apps/bitcoin/Cargo.toml, rust/apps/bitcoin/src/multi_sig/wallet.rs, rust/rust_c/CMakeLists.txt, rust/rust_c/Cargo.lock, rust/rust_c/Cargo.toml, rust/rust_c/src/common/src/ur.rs, rust/rust_c/src/common/src/ur_ext.rs, rust/rust_c/src/lib.rs, src/crypto/account_public_info.c, src/ui/gui_model/gui_model.c, ui_simulator/simulator.cmake, ui_simulator/simulator_model.c, ui_simulator/simulator_model.h
=> Add qrcode read to simulator

src/webusb_protocol/services/service_file_trans.c
=> add webusb md5 check

CMakeLists.txt, rust/apps/bitcoin/src/multi_sig/wallet.rs, rust/rust_c/src/bitcoin/src/multi_sig/structs.rs, src/tasks/qrdecode_task.c, src/tasks/qrdecode_task.h, src/ui/gui_analyze/gui_resolve_ur.c, src/ui/gui_analyze/gui_resolve_ur.h, src/ui/gui_model/gui_model.c, src/ui/gui_widgets/gui_scan_widgets.c, src/ui/gui_widgets/multi_sig/gui_multi_sig_import_wallet_info_widgets.c, src/ui/gui_widgets/multi_sig/gui_multi_sig_import_wallet_info_widgets.h, ui_simulator/simulator_model.c, ui_simulator/simulator_model.h
=> Multi sig UI

src/ui/lv_i18n/lv_i18n.c
=> fix taproot eg

src/user_fatfs.c, src/user_fatfs.h, test/test_cmd.c
=> 1. add read api

src/ui/gui_views/gui_views.c, src/ui/gui_views/gui_views.h, src/ui/lv_i18n/data.csv, src/ui/lv_i18n/lv_i18n.c
=> add wallet notice

src/managers/fingerprint_process.c, src/managers/screen_manager.c
=> revert sleep func

src/ui/gui_views/gui_views.c, src/ui/lv_i18n/data.csv
delete notice view while change wallet
=> delete notice view while change wallet

src/managers/screen_manager.c
=> sleep wakeup

src/managers/screen_manager.c
=> fix sleep wakeup

rust/rust_c/src/bitcoin/src/multi_sig/mod.rs
=> style: remove unused print

src/ui/gui_analyze/gui_resolve_ur.c, src/ui/gui_widgets/multi_sig/gui_multi_sig_import_wallet_info_widgets.c, src/ui/gui_widgets/multi_sig/gui_multi_sig_import_wallet_info_widgets.h, src/ui/lv_i18n/data.csv, src/ui/lv_i18n/lv_i18n.c
This PR add an interface to import multisig wallet from SDCard
=> feat(multisig): support import multisig wallet from sdcard

build.bat, src/ui/gui_widgets/btc_only/gui_create_multi_widgets.c, ui_simulator/simulator_model.h
=> add create multi wallet save

rust/apps/bitcoin/src/multi_sig/wallet.rs
=> change verify xyzpub

src/ui/gui_widgets/btc_only/gui_btc_wallet_profile_widgets.c
=> add testnet switch

src/ui/gui_widgets/btc_only/multi_sig/gui_manage_multisig_wallet_widgets.c
=> fix update text error

src/ui/gui_widgets/btc_only/multi_sig/gui_import_multisig_wallet_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_manage_multisig_wallet_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_transaction_signature_widgets.c
=> fix warning

src/ui/gui_widgets/gui_connect_wallet_widgets.c, src/ui/wallet/gui_wallet.c, ui_simulator/simulator_model.c
support multisig connect wallet
=> support multisig connect wallet

src/ui/gui_widgets/btc_only/multi_sig/gui_manage_multisig_wallet_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_select_import_method_widgets.c
=> fix(multisig): import wallet entry

CMakeLists.txt, src/ui/gui_widgets/btc_only/multi_sig/gui_create_multisig_wallet_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_wallet_export_widgets.c
=> fix address order

build.bat, src/ui/gui_widgets/btc_only/multi_sig/gui_create_multisig_wallet_widgets.c
fix create multisig return crash
=> fix create multisig return crash

src/ui/gui_widgets/gui_utxo_receive_widgets.c
=> fix single sig receive crash

CMakeLists.txt, external/lvgl/src/extra/libs/fsdrv/lv_fs_stdio.c, src/managers/btc_only/multi_sig_wallet_manager.c, src/managers/sdcard_manager.c, src/managers/sdcard_manager.h, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_transaction_signature_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_wallet_export_widgets.c, ui_simulator/simulator_model.c, ui_simulator/simulator_model.h
=> feat(multisig): support export wallet to sd card

CMakeLists.txt, src/crypto/account_public_info.c
=> fix simulator build

external/lvgl/src/extra/libs/fsdrv/lv_fs_stdio.c, ui_simulator/simulator_storage.c
=> feat(simulator): add fs always mode

src/managers/sdcard_manager.c, src/managers/sdcard_manager.h, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_transaction_signature_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_wallet_export_widgets.c, ui_simulator/simulator_storage.c
=> fix windows simulator

src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_transaction_signature_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_wallet_export_widgets.c
=> performance: memory refinement

src/ui/gui_widgets/btc_only/multi_sig/gui_create_multisig_wallet_widgets.c
fix multisig default chaintype
=> fix multisig default chaintype

src/ui/gui_widgets/btc_only/multi_sig/gui_create_multisig_wallet_widgets.c
=> add format button

src/ui/gui_widgets/btc_only/multi_sig/gui_create_multisig_wallet_widgets.c
=> add switch format title

src/ui/gui_widgets/btc_only/multi_sig/gui_create_multisig_wallet_widgets.c
=> change import xpub title

external/lvgl/src/extra/libs/fsdrv/lv_fs_stdio.c, src/ui/gui_components/gui_keyboard.c
=> fix: simulator on mac and a potential crash

src/ui/gui_widgets/btc_only/gui_btc_wallet_profile_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_manage_multisig_wallet_widgets.c
clear current address index when set current wallet
=> clear current address index when set current wallet

src/user_fatfs.c
=> fix(multisig): read file will cause rust panic

src/user_fatfs.c
=> fix(multisig): read file will crash

src/ui/gui_widgets/btc_only/multi_sig/gui_create_multisig_wallet_widgets.c
fix:hide the import xpub btn when return
=> fix:hide the import xpub btn when return

src/ui/gui_widgets/btc_only/multi_sig/gui_create_multisig_wallet_widgets.c, src/ui/lv_i18n/data.csv, src/ui/lv_i18n/lv_i18n.c
delete multisig wallet default name
=> delete multisig wallet default name

src/ui/gui_widgets/btc_only/gui_btc_home_widgets.c
set icon when current wallet switch
=> set icon when current wallet switch

rust/apps/bitcoin/src/multi_sig/wallet.rs
=> test(multisig): add unit tests

rust/rust_c/src/common/src/ur_ext.rs
=> fix multi coin build

src/ui/gui_widgets/btc_only/multi_sig/gui_manage_multisig_wallet_widgets.c, src/ui/gui_widgets/gui_export_pubkey_widgets.c
=> support export xpub

rust/apps/ethereum/src/eip712/eip712.rs, rust/apps/ethereum/src/eip712/serde_helpers.rs
=> fix: EIP712 salt parsing issue

src/ui/gui_widgets/btc_only/multi_sig/gui_import_multisig_wallet_info_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_transaction_signature_widgets.c
=> fix(multisig): check sd card before export / clear modal when deinit

src/crypto/account_public_info.c
=> fix simualtor

rust/apps/bitcoin/src/multi_sig/wallet.rs, src/ui/gui_components/gui_pending_hintbox.c, src/ui/gui_widgets/btc_only/multi_sig/gui_import_multisig_wallet_info_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_wallet_export_widgets.c
=> fix(multisig): meet error when strict verify my xpub

src/ui/gui_widgets/btc_only/gui_btc_wallet_profile_widgets.c
=> refresh current wallet status

src/ram/user_memory.h, src/ui/gui_widgets/btc_only/multi_sig/gui_create_multisig_wallet_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_read_sdcard_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_wallet_export_widgets.c, src/ui/gui_widgets/general/gui_multi_accounts_receive_widgets.c, src/ui/gui_widgets/general/gui_multi_path_coin_receive_widgets.c, src/ui/gui_widgets/general/gui_standard_receive_widgets.c, src/ui/gui_widgets/gui_connect_wallet_widgets.c, src/ui/gui_widgets/gui_export_pubkey_widgets.c, src/ui/gui_widgets/gui_select_address_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c, src/user_fatfs.c, src/utils/user_utils.c, src/utils/user_utils.h
=> support long name file

rust/rust_c/src/common/src/lib.rs, src/ui/gui_model/gui_model.c, src/ui/gui_views/gui_scan_view.c, src/ui/gui_views/gui_views.c, src/ui/gui_views/gui_views.h, src/ui/gui_widgets/gui_scan_widgets.c, src/ui/gui_widgets/gui_scan_widgets.h, src/ui/lv_i18n/data.csv, src/ui/lv_i18n/lv_i18n.c
=> feat(multisig): reject transactions that dont belong to current wallet

src/ui/gui_widgets/btc_only/multi_sig/gui_import_multisig_wallet_info_widgets.c
=> fix(multisig): close current view when error modal popup

src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_wallet_export_widgets.c
close export window when switch wallet
=> close export window when switch wallet

rust/apps/bitcoin/src/transactions/psbt/wrapped_psbt.rs, src/ui/gui_chain/btc/gui_btc.c, src/ui/gui_views/gui_views.c, src/ui/gui_widgets/gui_scan_widgets.c
=> fix(multisig): transaction verify failed always

src/ui/gui_chain/btc/gui_btc.c
=> fix(multisig): transaction verify failed always on sdcard

src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_wallet_export_widgets.c
destroy timer when close export wallet view
=> destroy timer when close export wallet view

src/ui/gui_widgets/btc_only/multi_sig/gui_manage_multisig_wallet_widgets.c
fix:update update multisig policy view
=> fix:update update multisig policy view

src/crypto/account_public_info.c, src/ui/gui_widgets/btc_only/multi_sig/gui_create_multisig_wallet_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_import_multisig_wallet_info_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_import_multisig_wallet_info_widgets.h, src/ui/gui_widgets/btc_only/multi_sig/gui_manage_multisig_wallet_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_read_sdcard_widgets.c
add error notice when file invalid
=> add error notice when file invalid

rust/apps/bitcoin/src/lib.rs, rust/apps/bitcoin/src/multi_sig/wallet.rs, rust/apps/bitcoin/src/transactions/legacy/parser.rs, rust/apps/bitcoin/src/transactions/parsed_tx.rs, rust/apps/bitcoin/src/transactions/psbt/parsed_psbt.rs, rust/apps/bitcoin/src/transactions/psbt/wrapped_psbt.rs, rust/rust_c/src/bitcoin/src/psbt.rs, rust/rust_c/src/bitcoin/src/structs.rs, src/ui/gui_chain/btc/gui_btc.c, src/ui/gui_widgets/btc_only/gui_btc_wallet_profile_widgets.c, src/ui/gui_widgets/gui_export_pubkey_widgets.c
=> feat(multisig): judge multisig change  or receive address

src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_read_sdcard_widgets.c
close error notice when switch wallet
=> close error notice when switch wallet

src/ui/gui_components/gui_hintbox.h, src/ui/gui_views/gui_views.c, src/ui/gui_views/gui_views.h, src/ui/gui_widgets/btc_only/multi_sig/gui_create_multisig_wallet_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_import_multisig_wallet_info_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_read_sdcard_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_select_import_method_widgets.c, src/ui/gui_widgets/gui_connection_widgets.c, src/ui/gui_widgets/gui_export_pubkey_widgets.c, src/ui/gui_widgets/gui_firmware_update_widgets.c, src/ui/gui_widgets/gui_forget_pass_widgets.c, src/ui/gui_widgets/gui_lock_device_widgets.c, src/ui/gui_widgets/gui_scan_widgets.c, src/ui/gui_widgets/gui_transaction_detail_widgets.c, src/ui/gui_widgets/gui_web_auth_result_widgets.c
=> fix(multisig): recall qrcode scan start when error modal close

src/ui/gui_views/gui_lock_view.c
=> disable lock screen wipe

rust/apps/bitcoin/src/multi_sig/wallet.rs
=> fix(multisig): XYZpub is invalid when parsing

src/ui/gui_chain/btc/gui_btc.c, src/ui/gui_views/gui_export_pubkey_view.c, src/ui/gui_widgets/gui_export_pubkey_widgets.c
support export multisig xpub qrcode
=> support export multisig xpub qrcode

src/utils/user_utils.c, ui_simulator/simulator_storage.c
=> support too lone name file

src/crypto/account_public_info.c, src/managers/se_manager.c, src/tasks/qrdecode_task.c, src/ui/gui_views/gui_lock_view.c
=> fix multisig hash check

src/managers/btc_only/multi_sig_wallet_manager.h, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_wallet_export_widgets.c
=> adjust pwsh-p2wsh show

rust/apps/bitcoin/src/lib.rs, rust/apps/bitcoin/src/transactions/legacy/parser.rs, rust/apps/bitcoin/src/transactions/parsed_tx.rs, rust/apps/bitcoin/src/transactions/psbt/wrapped_psbt.rs, rust/rust_c/src/bitcoin/src/structs.rs, src/crypto/account_public_info.c, src/ui/gui_chain/btc/gui_btc.c
=> feat(multisig): show input address receive/change tag

src/ui/gui_widgets/btc_only/gui_btc_home_widgets.c
=> fix(btc_only): a potential crash

src/ui/gui_chain/btc/gui_btc.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c
=> fix(multisig): sd card read signed psbt

src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_transaction_signature_widgets.c
=> fix(multisig): restart qr code updating in multisig signature

src/crypto/account_public_info.c
fix delete remove format string
=> fix delete remove format string

src/ui/gui_model/gui_model.c
refresh acountinfo info when set passphrase
=> refresh acountinfo info when set passphrase

src/ui/gui_widgets/btc_only/gui_btc_wallet_profile_widgets.c
hidden the multisig xpub export when passphrase set
=> hidden the multisig xpub export when passphrase set

src/crypto/account_public_info.c
wipe multisig config when delete wallet
=> wipe multisig config when delete wallet

src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_wallet_export_widgets.c
=> update p2sh wallet show

src/ui/gui_widgets/gui_scan_widgets.c
restart scan qrcode when micro not detected
=> restart scan qrcode when micro not detected

src/ui/gui_widgets/gui_utxo_receive_widgets.c, src/utils/user_utils.c
=> fix: multisig receive page ui

src/crypto/account_public_info.c, src/ui/gui_chain/others/gui_sol.c, src/ui/gui_widgets/gui_create_wallet_widgets.c, src/ui/gui_widgets/gui_import_phrase_widgets.c, src/ui/gui_widgets/setting/gui_wallet_setting_widgets.c, src/webusb_protocol/general/eapdu_protocol_parser.c, src/webusb_protocol/general/eapdu_services/service_check_lock.c, src/webusb_protocol/general/eapdu_services/service_export_address.c, src/webusb_protocol/general/eapdu_services/service_resolve_ur.c
1. add debug print
2. complement ext free
=> add debug info

src/ui/gui_widgets/btc_only/gui_btc_wallet_profile_widgets.c
=> hide create multisig entrance

src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_wallet_export_widgets.c
=> fix: do not show pending modal when exporting multisig wallet

src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_wallet_export_widgets.c, src/ui/gui_widgets/gui_import_phrase_widgets.c, src/ui/gui_widgets/setting/gui_wallet_setting_widgets.c
=> fix import wallet oom

src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_transaction_signature_widgets.c
=> fix(multisig): add a pending modal when transaction is signing

src/ui/gui_model/gui_model.c, src/ui/gui_widgets/gui_export_pubkey_widgets.c
=> fix: crash after export multisig xpub

src/tasks/qrdecode_task.c, src/ui/gui_chain/btc/gui_btc.c, src/ui/gui_frame/gui_resource.h, src/ui/gui_model/gui_model.c, src/ui/gui_widgets/btc_only/gui_btc_home_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_manage_multisig_wallet_widgets.c, src/ui/gui_widgets/gui_export_pubkey_widgets.c, src/ui/gui_widgets/gui_scan_widgets.c, src/ui/gui_widgets/gui_scan_widgets.h, src/ui/gui_widgets/gui_transaction_detail_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c, src/ui/lv_i18n/data.csv, src/ui/lv_i18n/lv_i18n.c, src/ui/lv_i18n/lv_i18n.h
=> feat: add sdcard sign option on more popup in home page

test/test_cmd.c
=> fix: multi-coin build

src/ui/gui_widgets/gui_setup_widgets.c, src/ui/gui_widgets/gui_system_setting_widgets.c, ui_simulator/simulator_storage.c
=> hide other language

src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_read_sdcard_widgets.c, src/ui/gui_widgets/gui_scan_widgets.c
=> fix(multisig): psbt from SDcard persists in the memory

src/ui/gui_widgets/btc_only/gui_btc_home_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_import_multisig_wallet_info_widgets.c, src/user_fatfs.c, src/utils/user_utils.c
=> switch setting order

src/ui/gui_views/gui_scan_view.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_read_sdcard_widgets.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_select_import_method_widgets.c, src/ui/gui_widgets/gui_scan_widgets.c, src/ui/gui_widgets/gui_scan_widgets.h
=> refactor: remove unused code

src/crypto/account_public_info.c, src/ui/gui_components/gui_status_bar.c, src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_read_sdcard_widgets.c
fix error case regenerate pubkey
=> fix error case regenerate pubkey

rust/apps/bitcoin/src/multi_sig/wallet.rs, src/ui/gui_widgets/btc_only/multi_sig/gui_manage_multisig_wallet_widgets.c
=> feat: disable multisig testnet wallet

src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_select_import_method_widgets.c
close notice window when switch wallet
=> close notice window when switch wallet

rust/apps/bitcoin/src/multi_sig/address.rs, rust/apps/bitcoin/src/multi_sig/wallet.rs
=> test: fix bitcoin unit test

src/ui/gui_components/gui_status_bar.c
hide the testnet icon at lock view
=> hide the testnet icon at lock view

src/crypto/account_public_info.c, src/managers/se_manager.c
=> delete unused code

src/user_fatfs.c
=> add file size limit

src/config/version.c, src/config/version_btc_only.h, src/webusb_protocol/services/service_device_info.c
=> webusb update version

src/ui/gui_analyze/gui_analyze.c, src/ui/gui_chain/others/gui_eth.c, ui_simulator/simulator_model.c
=> support eth simulator

src/ui/gui_analyze/gui_analyze.c, src/ui/gui_chain/others/gui_eth.c, ui_simulator/simulator_model.c, ui_simulator/simulator_model.h
=> fix: transaction parse failed

src/ui/gui_widgets/gui_create_wallet_widgets.c, src/ui/lv_i18n/data.csv, src/ui/lv_i18n/lv_i18n.c
=> fix dice bg cont opa

src/ui/gui_model/gui_model.c, src/ui/gui_widgets/gui_lock_widgets.c
=> fix lose name and icon

src/ui/gui_widgets/btc_only/multi_sig/gui_multisig_transaction_signature_widgets.c, src/ui/gui_widgets/gui_transaction_signature_widgets.c
=> fix: hide pending modal when signing transaction for btc_only now

rust/apps/bitcoin/src/lib.rs, rust/apps/bitcoin/src/transactions/legacy/parser.rs, rust/apps/bitcoin/src/transactions/parsed_tx.rs, rust/apps/bitcoin/src/transactions/psbt/parsed_psbt.rs, rust/apps/bitcoin/src/transactions/psbt/wrapped_psbt.rs, src/ui/gui_chain/btc/gui_btc.c
=> fix: unisat listing transaction bug

src/ui/gui_chain/btc/gui_btc.c
=> fix: unisat bug

rust/apps/ethereum/src/eip712/eip712.rs, rust/apps/ethereum/src/lib.rs, rust/keystore/Cargo.lock
=> fix cosmos dym vote signing

rust/apps/ethereum/Cargo.lock, rust/apps/ethereum/src/eip712/eip712.rs, rust/apps/ethereum/src/lib.rs
=> cosmos sig : fix dym vote signing

rust/apps/cardano/src/structs.rs
=> performance(cardano): disable multi assets parsing currently to save memory

rust/apps/cardano/src/structs.rs, src/ui/gui_chain/others/gui_ada.c, ui_simulator/.gitignore, ui_simulator/tools/read_then_write_json.mjs
=> Fix ada simulator

src/ui/gui_widgets/gui_connect_wallet_widgets.c
=> feat: change unisat order

src/ui/gui_model/gui_model.c
=> fix checksum crash

rust/apps/ethereum/src/eip712/eip712.rs, rust/apps/ethereum/src/eip712/serde_helpers.rs, rust/apps/ethereum/src/lib.rs
=> Support non standard eip 712

src/ui/gui_widgets/gui_connect_wallet_widgets.c
=> feat: close unisat entry currently

docs/verify.md
This PR updates the doc/verify.md to match current state.
=> doc: update verify document

docs/verify.md
Update doc for more detail instruction
No need
=> doc:update the doc to add more detail instruction

docs/verify.md
=> doc: update doc

src/ui/gui_widgets/general/gui_multi_accounts_receive_widgets.c, src/ui/gui_widgets/general/gui_multi_path_coin_receive_widgets.c, src/ui/gui_widgets/general/gui_standard_receive_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c, src/ui/gui_widgets/setting/gui_setting_widgets.c
=> fix ui bugs

src/ui/gui_widgets/general/gui_multi_accounts_receive_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c, src/ui/lv_i18n/data.csv
=> delete address dot

src/ram/user_memory.h, src/ui/gui_views/gui_system_setting_view.c, src/ui/gui_widgets/general/gui_key_derivation_request_widgets.c, src/ui/gui_widgets/gui_enter_passcode.h, src/ui/gui_widgets/gui_lock_widgets.h
=> build: fix simulator

src/ui/gui_analyze/gui_analyze.c, src/ui/gui_chain/others/gui_ada.c
=> fix(cardano): transaction crash

src/ui/gui_widgets/general/gui_multi_accounts_receive_widgets.c
=> fix ada switch account align

src/ui/gui_components/gui_status_bar.c
Update wallet names for Eternl and Typhon
=> FIX: Update wallet names for Eternl and Typhon

src/ui/gui_components/gui_status_bar.c, src/ui/gui_components/gui_status_bar.h, src/ui/gui_widgets/gui_system_setting_widgets.c
=> fix btc only build

src/ui/gui_views/gui_lock_view.c
get wallet name after fingerprint unlock device
=> get wallet name after fingerprint unlock device

src/ui/gui_widgets/gui_connect_wallet_widgets.c
Clean up connect wallet widgets
=> fix: Clean up connect wallet widgets

src/ui/gui_assets/font/rus/ruLittleTitle.c, src/ui/gui_components/gui_status_bar.c, src/ui/gui_widgets/setting/gui_fingerprint_widgets.c
=> update undo btn style

src/ui/gui_components/gui_status_bar.c
=> update word select btn style

src/ui/gui_widgets/gui_create_wallet_widgets.c
deinit change entropy page when switch wallet
=> deinit change entropy page when switch wallet

src/ui/gui_chain/btc/gui_btc.c, src/ui/gui_chain/others/gui_ada.c
=> Fix several UI issues

src/ui/gui_chain/btc/gui_btc.c
=> fix: utxo fee should be white when fee is not larger than amount

build.py
=> fix: fix hash calculate logic

src/ui/gui_widgets/gui_connect_wallet_widgets.c
=> fix: open unisat walletlist

src/config/version.h
=> build:update version

src/ui/gui_widgets/gui_wallet_tutorial_widgets.c
=> fix: fix tutorial qr code color

src/ui/gui_widgets/general/gui_home_widgets.c
=> fix crash when switch wallet

src/ui/gui_widgets/gui_connect_wallet_widgets.c
=> fix: unisat text

src/ui/gui_assets/font/cn/cnIllustrate.c, src/ui/gui_assets/font/cn/cnLittleTitle.c, src/ui/gui_assets/font/cn/cnText.c, src/ui/gui_assets/font/cn/cnTitle.c, src/ui/gui_assets/font/ko/koIllustrate.c, src/ui/gui_assets/font/ko/koLittleTitle.c, src/ui/gui_assets/font/ko/koText.c, src/ui/gui_assets/font/ko/koTitle.c, src/ui/gui_assets/font/rus/ruIllustrate.c, src/ui/gui_assets/font/rus/ruLittleTitle.c, src/ui/gui_assets/font/rus/ruText.c, src/ui/gui_assets/font/rus/ruTitle.c
=> chore: Unify multilingual layout

src/ui/gui_components/gui_attention_hintbox.c
Calculate dynamic button content width
=> fix(i18n): Calculate dynamic button content width

src/ui/gui_widgets/general/gui_home_widgets.c
=> fix: crash when switch wallet

src/ui/gui_assets/font/ru/ruIllustrate.c, src/ui/gui_assets/font/ru/ruLittleTitle.c, src/ui/gui_assets/font/ru/ruText.c, src/ui/gui_assets/font/ru/ruTitle.c
=> update ru font

src/ui/gui_widgets/gui_wallet_tutorial_widgets.c
fix wallet tutorial widgets qrcode img
=> fix: fix wallet tutorial widgets qrcode img

src/ui/gui_components/gui_status_bar.c, src/ui/gui_widgets/gui_firmware_update_widgets.c, src/ui/gui_widgets/gui_firmware_update_widgets.h
=> fix sdcard bin check ui bugs

src/ui/gui_widgets/gui_firmware_update_widgets.h, src/ui/gui_widgets/gui_scan_widgets.c
=> fix: fix simulator issue & remove loading

src/ui/gui_views/gui_connect_wallet_view.c
=> chore: Update signal names

.github/workflows/rust-fmt-checks.yml, src/ui/gui_chain/others/gui_ar.c
=> chore: Add rust-fmt-checks workflow

src/ui/gui_model/gui_model.c
=> fix(simulator): tx check is ignored

src/ui/gui_components/gui_attention_hintbox.c
=> swap button positions

src/ui/gui_views/gui_init_view.c
fixed the shutdown option not being enabled in Japanese
=> fixed the shutdown option not being enabled in Japanese

src/crypto/account_public_info.c, src/ui/gui_model/gui_model.c
=> fix(ton): forget password not working

src/ui/gui_views/gui_views.c, src/ui/gui_views/gui_views.h, src/ui/gui_widgets/gui_forget_pass_widgets.c
=> fix forget password crash

src/ui/gui_widgets/general/gui_home_widgets.c
=> fix(ton): disable some coins

src/ui/gui_widgets/gui_transaction_signature_widgets.c
=> fix(ton): transaction signature page title

src/crypto/account_public_info.c
=> fix: slip39 wallet cannot setup AR

src/driver/low_power.c, src/tasks/ui_display_task.c
1. Increase the wakeup interval during sleep
2. Lights up the screen when waking up the device in some case
=> fix device can't wakeup

src/ui/gui_chain/others/gui_sol.c
=> fix sol unknown overview layout

src/ui/gui_widgets/general/gui_standard_receive_widgets.c, src/ui/wallet/gui_wallet.c, src/ui/wallet/gui_wallet.h
fix int overflow and modify btn style
=> fix int overflow and modify btn style

src/ui/gui_widgets/gui_select_address_widgets.c
feat: add keplr confirm btn style
=> feat: add keplr confirm btn style

src/ui/gui_widgets/gui_connect_wallet_widgets.c
=> fix: update Backpack support networks

README.md
Update the readme file
No Need test
=> fix: Update README.md for code clone part

docs/SIMULATOR.md
=> docs: add some tricks explanation to the simulator document

docs/SIMULATOR.md
=> docs: fix typo

docs/SIMULATOR.md
=> docs: update simulator setup doc

src/ui/gui_widgets/general/gui_standard_receive_widgets.c
remove apt sui xrp jump button
=> fix: remove apt sui xrp jump button

src/ui/gui_chain/others/gui_ar.c
=> chore: fix build

src/ui/gui_analyze/gui_analyze.c
=> Fix: update GUI analyze page layout

src/driver/drv_battery.c
=> Battery charging refactor

src/driver/drv_battery.c
adjust charging/discharge percent
=> adjust charging/discharge percent

src/ui/gui_chain/others/gui_sol.c, src/ui/gui_components/gui_qr_hintbox.c
add scrollable area for lang content
=> feat: add scrollable area for lang content

src/ui/gui_widgets/gui_connect_wallet_widgets.c
=> fix(ar): password verify failed ui error when connect wallet

rust/rust_c/src/common/src/qrcode/mod.rs
=> fix(sparrow): sign message error

src/ui/gui_components/gui_status_bar.c
=> chore: update wallet name to xBull

rust/rust_c/src/solana/src/structs.rs, src/ui/gui_chain/others/gui_sol.c
=> fix: fix memory leak

src/driver/drv_battery.c
=> adjust battery charging

src/ui/gui_widgets/gui_connect_wallet_widgets.c
=> fix: remove dot icon

rust/apps/xrp/Cargo.lock, rust/apps/xrp/rust-toolchain, rust/apps/xrp/src/lib.rs, rust/apps/xrp/src/parser/mod.rs, rust/rust_c/src/common/src/ur_ext.rs, rust/rust_c/src/xrp/src/lib.rs, rust/rust_c/src/xrp/src/structs.rs, src/ui/gui_chain/others/gui_xrp.c, src/ui/gui_widgets/gui_connect_wallet_widgets.c
add hot app version v2 xrp transaction
=> feat: add xrp payment support

rust/apps/wallets/src/keystone.rs
add keystone 3 pro cold wallet version field
=> feat: add keystone cold wallet version

README.md
=> docs: update readme astyle command

rust/apps/bitcoin/src/lib.rs, rust/apps/bitcoin/src/transactions/legacy/parser.rs, rust/apps/wallets/src/keystone.rs, src/ui/gui_chain/btc/gui_btc.c
fix btc parse view ui 
update cold wallet version to 31506
=> fix: fix btc parse view ui and update cold wallet version to 31506

rust/apps/bitcoin/src/lib.rs, rust/apps/bitcoin/src/transactions/legacy/parser.rs, src/ui/gui_chain/btc/gui_btc.c, src/ui/gui_widgets/gui_connect_wallet_widgets.c
1、update wallet list show logic 
2、update label show logic
=> update wallet list show logic 

rust/rust_c/Cargo.lock, src/ui/gui_components/gui_status_bar.c
=> fix: wallet icon wrong order

src/ui/gui_widgets/gui_connect_wallet_widgets.c
=> fix: move tonkeeper

src/ui/gui_chain/others/gui_ton.c
=> fix(ton): slip39 support

src/ui/gui_chain/others/gui_ton.c
=> fix(ton): slip39 tonconnect

rust/apps/ethereum/src/legacy_transaction.rs, src/ui/gui_chain/others/gui_ton.c
=> merge to release 1.5.8 

rust/rust_c/src/xrp/src/lib.rs, src/ui/gui_chain/others/gui_xrp.c
fix xrp signature and add distinguish xrp tx type
=> fix: fix xrp signature and add distinguish xrp tx type

rust/apps/ethereum/src/legacy_transaction.rs, rust/rust_c/src/xrp/src/lib.rs, src/ui/gui_chain/others/gui_xrp.c
fix xrp signature and add distinguish xrp tx type
=> fix xrp signature and add distinguish xrp tx type

src/ui/gui_model/gui_model.c
fix:close finger signer when forget password
=> fix:close finger signer when forget password

rust/apps/cardano/Cargo.toml, rust/apps/cardano/src/structs.rs, rust/apps/cardano/src/transaction.rs, rust/rust_c/src/cardano/src/lib.rs, rust/rust_c/src/cardano/src/structs.rs, rust/third_party/Cargo.toml, src/ui/gui_analyze/gui_analyze.c, src/ui/gui_chain/others/gui_ada.c, src/ui/gui_chain/others/gui_ada.h, src/ui/gui_chain/others/gui_ton.c, src/ui/gui_components/gui_status_bar.c
=> feat: update signdata display

rust/apps/wallets/src/bitget.rs, rust/rust_c/src/wallet/src/multi_coins_wallet/src/bitget.rs, src/ui/gui_widgets/gui_connect_wallet_widgets.c, src/ui/wallet/gui_wallet.c, src/ui/wallet/gui_wallet.h
add change eth select derivation path feat
=> feat: add change eth select derivation path feat

src/ui/lv_i18n/data.csv, src/ui/lv_i18n/lv_i18n.c
=> fix: fix i18n csv content

src/crypto/account_public_info.c, src/ui/gui_widgets/general/gui_multi_accounts_receive_widgets.c
=> fix: passphrase and slip39 issues in ADA

src/ui/gui_chain/others/gui_ada.c, src/ui/gui_widgets/general/gui_key_derivation_request_widgets.c, src/ui/gui_widgets/gui_change_path_type_widgets.c
=> fix: sample address calculation error

src/driver/drv_battery.c
=> battery discharge adjust

rust/apps/cardano/src/address.rs, rust/rust_c/src/cardano/src/lib.rs, src/ui/gui_chain/others/gui_ada.c
=> fix: Update ADA derivation in GUI widget for displaying Ada sign data

src/ui/gui_widgets/gui_low_battery_widgets.c
resize low battery button size
=> fix:low battery button size

src/ui/gui_widgets/general/gui_key_derivation_request_widgets.c
=> fix: fix curve to public key type logic

CHANGELOG-ZH.md, CHANGELOG.md
=> add 1.6.0 changelogs

src/webusb_protocol/services/service_file_trans.c
add nft transfer signature verify
=> add nft transfer signature verify

src/ui/gui_widgets/gui_display_widgets.c
=> clear nft switch clickable

src/tasks/ui_display_task.c, src/tasks/ui_display_task.h, src/ui/gui_widgets/gui_lock_widgets.c
fix:clear nft window when finger detect
=> fix:clear nft window when finger detect

README.md
Add the code structure part for issue #1272 
@ww3512687 @soralit please review the code structure description
No need test
=> feat: add the code structure part in the readme

rust/apps/solana/src/parser/mod.rs
=> fix: remove spl parse comment

src/driver/drv_battery.c
=> fix:adjust battery percent

CHANGELOG-ZH.md, CHANGELOG.md
=> modify changelog

src/ui/gui_chain/others/gui_sol.c, src/ui/gui_views/gui_init_view.c, src/ui/gui_widgets/gui_lock_widgets.c
1、add text long wrap mode and hide desc compnent
=> Fix/fix squads UI

src/ui/gui_analyze/gui_analyze.c, src/ui/gui_chain/btc/gui_btc.c
=> fix: sparrow sign message

src/crypto/account_public_info.c, src/crypto/account_public_info.h, src/ui/gui_widgets/general/gui_multi_accounts_receive_widgets.c, src/ui/gui_widgets/general/gui_multi_path_coin_receive_widgets.c, src/ui/gui_widgets/general/gui_standard_receive_widgets.c, src/ui/gui_widgets/gui_change_path_type_widgets.c, src/ui/gui_widgets/gui_connect_wallet_widgets.c, src/ui/gui_widgets/gui_utxo_receive_widgets.c
1. account storge
3. connect path storge
=> account storge

src/ui/gui_chain/btc/gui_btc.c
=> fix(btc): transaction error

src/ui/gui_widgets/gui_connect_wallet_widgets.c
=> fix:mm and solfare pathtype

rust/apps/solana/src/parser/mod.rs, src/ui/gui_chain/others/gui_sol.c
add solana network priority fee field
=> feat: add network priority fee support for squads

CMakeLists.txt, src/crypto/account_public_info.c, src/crypto/account_public_info.h, src/ui/gui_chain/others/gui_ada.c, src/ui/gui_widgets/general/gui_home_widgets.c, src/ui/gui_widgets/gui_connect_wallet_widgets.c
=> fix account storge bugs

src/crypto/account_public_info.c, src/ui/gui_widgets/gui_connect_wallet_widgets.c
fix:xrp、blockwallet、yearn wallet cannot save
=> fix:xrp、blockwallet、yearn wallet cannot save

src/ui/gui_chain/others/gui_ada.c, src/ui/gui_chain/others/gui_ada.h, src/ui/gui_widgets/gui_change_path_type_widgets.c
=> fix: issue with changing receive address

src/crypto/account_public_info.c
fix:clear passphrase temp account info when switch wallet
=> fix:clear passphrase temp account info when switch wallet

src/crypto/account_public_info.c
fix:clear account storge when switch passphrase wallet
=> fix:clear account storge when switch passphrase wallet

src/ui/gui_chain/others/gui_sol.c
=> fix: fix field name

src/ui/gui_chain/others/gui_ada.c, src/ui/gui_chain/others/gui_ada.h, src/ui/gui_model/gui_model.c, src/ui/gui_widgets/general/gui_key_derivation_request_widgets.c, src/ui/gui_widgets/general/gui_key_derivation_request_widgets.h, src/ui/gui_widgets/general/gui_multi_accounts_receive_widgets.c, src/ui/gui_widgets/general/gui_multi_path_coin_receive_widgets.c
=> fix:save ada coin receive info

src/tasks/ui_display_task.c
=> fix:Input pin delay

src/ui/gui_components/gui_status_bar.c
=> fix:battery percent update

src/crypto/account_public_info.c, src/ui/gui_widgets/general/gui_key_derivation_request_widgets.c
=> fix:save begin wallet storge

src/ui/gui_widgets/general/gui_key_derivation_request_widgets.c
fix:enable lock device after key derivation
=> fix:enable lock device after key derivation

src/ui/gui_widgets/gui_connect_wallet_widgets.c
=> fix: fix helium wallet order

src/ui/gui_components/gui_status_bar.c, src/ui/gui_widgets/gui_connect_wallet_widgets.c, src/ui/gui_widgets/gui_connect_wallet_widgets.h, src/ui/wallet/gui_wallet.c, src/ui/wallet/gui_wallet.h
refactor connect helium wallet logic
=> fix: refactor helium wallet change path logic

src/tasks/ui_display_task.c
=> fix crash after reboot

src/ui/gui_widgets/gui_connect_wallet_widgets.c
=> fix: fix solflare wallet crash

external/mh1903_lib/SCPU_USB_Lib/SCPU_USB_Device_Library/Class/cdc/src/usbd_cdc_core.c, src/main.c, src/ui/gui_views/gui_firmware_update_view.c, src/ui/gui_views/gui_ton_mnemonic_hint_view.c, src/ui/gui_widgets/general/gui_home_widgets.c, src/ui/gui_widgets/general/gui_key_derivation_request_widgets.c, src/ui/gui_widgets/general/gui_standard_receive_widgets.c, src/ui/gui_widgets/general/gui_usb_transport_widgets.c, src/ui/gui_widgets/gui_change_path_type_widgets.c, src/ui/gui_widgets/gui_connect_wallet_widgets.c, src/ui/gui_widgets/gui_firmware_update_widgets.c, src/ui/gui_widgets/gui_import_phrase_widgets.c, src/ui/gui_widgets/gui_nft_screen_widgets.c, src/webusb_protocol/general/eapdu_services/service_export_address.c, src/webusb_protocol/protocol_parse.c
=> delete debug code

external/mh1903_lib/SCPU_USB_Lib/SCPU_USB_Device_Library/Class/cdc/src/usbd_cdc_core.c, src/driver/drv_mpu.c, src/driver/drv_mpu.h, src/tasks/usb_task.c, src/ui/gui_widgets/general/gui_key_derivation_request_widgets.c
=> fix usb connect bugs

src/main.c, src/tasks/data_parser_task.h, src/ui/gui_components/gui_status_bar.c
=> fix battery percent

src/ui/gui_widgets/general/gui_key_derivation_request_widgets.c
=> fix simulator building

src/crypto/account_public_info.c, src/ui/gui_widgets/general/gui_multi_accounts_receive_widgets.c, src/ui/gui_widgets/general/gui_multi_path_coin_receive_widgets.c, src/ui/gui_widgets/gui_change_path_type_widgets.c
1、fix hnt and solana multi path receive logic
=> fix: fix hnt sol multi path logic

src/ui/gui_widgets/gui_import_phrase_widgets.c
=> fix: ton code missing after rebase

src/ui/gui_chain/gui_chain.c
=> disable btc usb sign

src/ui/gui_components/gui_status_bar.c
=> fix: fix helium wallet name

src/ui/gui_widgets/general/gui_key_derivation_request_widgets.c
=> fix connect eternal wallet

src/webusb_protocol/services/service_file_trans.c
add nft file signture after trans over
=> add nft file signture after trans over

src/webusb_protocol/general/eapdu_services/service_resolve_ur.c
add page limit when usb connect wallet
=> add page limit when usb connect wallet

external/mh1903_lib/SCPU_USB_Lib/SCPU_USB_Device_Library/Class/cdc/src/usbd_cdc_core.c
=> fix usb connect bug

src/ui/gui_widgets/general/gui_key_derivation_request_widgets.c
=> fix: fix hardware call seed len

src/ui/gui_chain/others/gui_cosmos.c
fix: update parse thorchain parse  tx icon
=> fix: update parse thorchain parse  tx icon

rust/apps/cardano/Cargo.lock, rust/apps/cardano/Cargo.toml, rust/rust_c/Cargo.lock
=> fix: cardano-serilization-lib cargo.toml error

rust/apps/wallets/src/bitget.rs, src/ui/wallet/gui_wallet.c
=> feat: add ton for bitget

src/ui/gui_views/gui_lock_view.c, src/ui/gui_widgets/gui_system_setting_widgets.c
=> fix language switch bugs

rust/apps/solana/src/solana_lib/jupiter_v6/instructions.rs
=> fix: update jupiter idl

rust/rust_c/Cargo.toml, rust/rust_c/cbindgens/develop/btc_only.toml, rust/rust_c/src/bitcoin/src/multi_sig/mod.rs, rust/rust_c/src/lib.rs, rust/rust_c/src/simulator/Cargo.toml, src/tasks/usb_task.c, src/ui/gui_chain/btc/gui_btc.c, src/ui/gui_views/gui_lock_view.c, src/ui/wallet/gui_wallet.c, src/ui/wallet/gui_wallet.h, src/webusb_protocol/services/service_file_trans.c
=> fix: build on btc-only

src/tasks/usb_task.c, src/webusb_protocol/services/service_file_trans.c
=> fix upgrade failed

rust/rust_c/src/bitcoin/src/psbt.rs, src/ui/gui_chain/btc/gui_btc.c, src/ui/gui_chain/btc/gui_btc.h, src/ui/gui_chain/gui_chain.c, src/ui/gui_widgets/gui_select_address_widgets.c, src/ui/gui_widgets/gui_transaction_detail_widgets.c, src/webusb_protocol/general/eapdu_services/service_resolve_ur.c
=> support btc usb

src/ui/gui_chain/others/gui_eth.c
=> fix: change unknown erc20 token name to fit ui

src/tasks/background_task.c
=> fix: increase heap memory

rust/apps/cardano/src/structs.rs
=> fix: handle case when transaction has no outputs

src/crypto/account_public_info.c
fix select account path by wallet name logic
=> fix: fix select account path by wallet name logic

src/crypto/account_public_info.c, src/ui/gui_components/gui_status_bar.c
1、remove unnecessary logic code for format wallet name
=> fix: update connect wallet logic

src/ui/gui_widgets/gui_connect_wallet_widgets.c
1、fix connect wallet show eg address logic
=> fix: fix  connect wallet show eg address logic

src/crypto/account_public_info.c, src/ui/gui_widgets/gui_connect_wallet_widgets.c
=> fix connnect wallet store

Dockerfile, tools/code/firmware-checker/Cargo.lock, tools/code/firmware-maker/Cargo.lock
=> chore: update docker file and tools lock

src/ui/gui_chain/others/gui_ada.c
=> Fix: Ada output detail size calculation

src/ui/gui_analyze/gui_analyze.c
=> Fix: null pointer dereference in GuiAnalyzeFreeTable

rust/apps/bitcoin/src/addresses/address.rs, rust/apps/bitcoin/src/network.rs, rust/apps/bitcoin/src/transactions/legacy/parser.rs, rust/apps/bitcoin/src/transactions/legacy/tx_data.rs, rust/apps/bitcoin/src/transactions/parsed_tx.rs, rust/apps/bitcoin/src/transactions/psbt/parsed_psbt.rs, rust/apps/bitcoin/src/transactions/psbt/wrapped_psbt.rs
add fractal btc support
run test
=> add fractal btc support

src/driver/drv_battery.c, src/driver/drv_lcd_bright.c
=> fix:battery adjust

ui_simulator/simulator_model.c
=> fix: simulator cannot sign transaction

src/ui/gui_widgets/gui_transaction_detail_widgets.c
=> fix sign condition

src/ui/gui_widgets/general/gui_home_widgets.c
=> fix home widgets bugs

src/ui/gui_chain/others/gui_eth.c, src/ui/gui_frame/gui_obj.c, src/ui/gui_frame/gui_obj.h, src/ui/gui_widgets/gui_transaction_detail_widgets.c
=> fix eth permit bug

src/ui/gui_chain/others/gui_eth.c
=> fix permit bug

src/ui/gui_views/gui_views.c
refresh home after create wallet
=> refresh home after create wallet

src/ui/gui_widgets/general/gui_home_widgets.c
=> Fixed blank area click bug

src/webusb_protocol/general/eapdu_services/service_resolve_ur.c
=> fix usb sign crash

external/lvgl/src/extra/widgets/keyboard/lv_keyboard.c
=> fix switch keyboard bug

src/ui/gui_widgets/general/gui_home_widgets.c
The receive page displays the error data
=> The receive page displays the error data

src/webusb_protocol/general/eapdu_services/service_resolve_ur.c
Reverts KeystoneHQ/keystone3-firmware#1452
=> Revert "fix usb sign crash"

rust/rust_c/src/arweave/src/lib.rs, rust/rust_c/src/bitcoin/src/address.rs, rust/rust_c/src/bitcoin/src/msg.rs, rust/rust_c/src/bitcoin/src/psbt.rs, rust/rust_c/src/cardano/src/lib.rs, rust/rust_c/src/cardano/src/structs.rs, rust/rust_c/src/common/src/keystone.rs, rust/rust_c/src/common/src/lib.rs, rust/rust_c/src/common/src/ur.rs, rust/rust_c/src/common/src/ur_ext.rs, rust/rust_c/src/common/src/web_auth.rs, rust/rust_c/src/ethereum/src/lib.rs, rust/rust_c/src/wallet/src/btc_only_wallet/src/lib.rs, rust/rust_c/src/wallet/src/multi_coins_wallet/src/aptos.rs, rust/rust_c/src/wallet/src/multi_coins_wallet/src/solana.rs, rust/rust_c/src/wallet/src/multi_coins_wallet/src/sui.rs, rust/rust_c/src/wallet/src/multi_coins_wallet/src/xbull.rs
1 run cargo  fmt and ./astyle.sh
=> chore: run astyle and cargo fmt

src/webusb_protocol/general/eapdu_services/service_resolve_ur.c
=> fix connect wallet crash

src/ui/gui_components/gui_attention_hintbox.c
1、 force flush settings data to storage
=> fix: force flush settings data to storage

src/ui/lv_i18n/lv_i18n.c
=> run font srcipt

rust/apps/solana/src/parser/mod.rs, rust/apps/solana/src/solana_lib/squads_v4/instructions.rs
1、update squads multisig create v2 parse
=> feat: add suqads multisig create2 support

rust/apps/cosmos/src/transaction/utils.rs, src/ui/gui_components/gui_status_bar.c
=> fix: fix ui

src/ui/gui_chain/btc/gui_btc.c
=> fix: non-btc utxo chains parse error

test/test_cmd.c
=> fix: fix test cmd

src/ui/lv_i18n/data.csv, src/ui/lv_i18n/lv_i18n.c
1、fix cardano derive address algo name
=> fix: fix cardano derive address algo name

src/ui/gui_model/gui_model.c, src/ui/gui_widgets/gui_create_share_widgets.c
slip39 error scenario causes the import to fail
=> slip39 error scenario causes the import to fail

src/crypto/account_public_info.c, src/crypto/account_public_info.h, src/managers/account_manager.c, src/managers/keystore.c, src/ui/gui_analyze/gui_analyze.c, src/ui/gui_chain/others/gui_ada.c, src/ui/gui_chain/others/gui_ada.h, src/ui/gui_chain/others/gui_sol.c, src/ui/gui_chain/others/gui_zcash.c, src/ui/gui_components/gui_status_bar.c, src/ui/gui_views/gui_transaction_detail_view.c, src/ui/gui_widgets/general/gui_standard_receive_widgets.c, src/ui/gui_widgets/gui_wallet_tutorial_widgets.c, src/ui/lv_i18n/lv_i18n.c, src/ui/wallet/gui_wallet.c
=> sign message address update

src/crypto/account_public_info.c, src/ui/gui_chain/others/gui_sol.c
=> fix sign message bug

rust/Cargo.lock, rust/rust_c/Cargo.toml, rust/rust_c/src/common/ur_ext.rs
=> Fix cypherpunk build

CMakeLists.txt, src/crypto/rsa.c, src/ui/gui_model/gui_model.c
=> fix web3 build

src/crypto/account_public_info.c
=> fix zcash crash

rust/apps/wallets/src/keystone.rs
=> fix companion app connection wallet stuck

rust/apps/wallets/src/keystone.rs
=> fix: keystone wallet connect

src/tasks/fetch_sensitive_data_task.c, src/ui/gui_frame/gui_obj.h, src/ui/gui_views/gui_views.h, src/ui/gui_views/multi/cypherpunk/gui_check_delete_wallet_view.c, src/ui/gui_widgets/gui_lock_widgets.c, src/ui/gui_widgets/multi/cypherpunk/gui_check_delete_wallet_widgets.c, src/ui/gui_widgets/multi/cypherpunk/gui_check_delete_wallet_widgets.h
=> fix zcrash crash

src/ui/gui_chain/multi/cypherpunk/gui_monero.c, src/ui/gui_wallet/btc_only/gui_wallet.h, src/ui/gui_wallet/multi/cypherpunk/gui_wallet.h, src/ui/gui_widgets/multi/cypherpunk/gui_check_delete_wallet_widgets.h, src/ui/gui_widgets/multi/gui_change_path_type_widgets.c
=> fix: build on simulator

src/crypto/account_public_info.c
fix cypherpunk wallet default coin
=> fix cypherpunk wallet default coin

src/device_settings.c, src/ui/gui_views/gui_passphrase_view.c
=> fix device setting save error

rust/rust_c/src/common/ur.rs
=> feat: open qr hardware call

src/ui/gui_wallet/btc_only/gui_wallet.c, src/ui/gui_wallet/multi/web3/gui_wallet.c, src/ui/gui_widgets/multi/gui_key_derivation_request_widgets.c, src/ui/gui_widgets/multi/gui_standard_receive_widgets.c
=> 1. fix usb get xpub crash

src/ui/gui_analyze/gui_analyze.c, src/ui/gui_analyze/gui_resolve_ur.c
=> disable key derivation ur type

src/ui/gui_chain/multi/web3/gui_sol.c, src/webusb_protocol/general/eapdu_protocol_parser.c, src/webusb_protocol/general/eapdu_services/service_check_lock.c, src/webusb_protocol/general/eapdu_services/service_export_address.c, src/webusb_protocol/general/eapdu_services/service_get_device_info.c, src/webusb_protocol/general/eapdu_services/service_resolve_ur.c, ui_simulator/simulator_storage.c
=> fix Xverse sign error

ui_simulator/simulator_storage.c
=> fix simulator

rust/apps/ethereum/src/lib.rs, rust/apps/ethereum/src/structs.rs, src/ui/gui_chain/others/gui_eth.c
=> fix: ui render error when typed data is large

src/ui/gui_widgets/multi/cypherpunk/gui_check_delete_wallet_widgets.c
=> enable fp detect after cancel delete wallet

src/ui/gui_widgets/multi/cypherpunk/gui_check_delete_wallet_widgets.c
Reverts KeystoneHQ/keystone3-firmware#1564
=> Revert "enable fp detect after cancel delete wallet"

src/ui/gui_chain/gui_chain.c
=> fix: avax merge issue

src/ui/gui_chain/multi/web3/gui_ton.c
=> chore: fix build on macOS

docs/protocols/ur_registrys/zcash.md
=> docs: update zcash docs

src/ui/gui_chain/multi/web3/gui_cosmos.c, src/ui/gui_chain/multi/web3/gui_cosmos.h, src/ui/gui_widgets/multi/gui_standard_receive_widgets.c
=> fix cosmos coin manage

rust/apps/avalanche/src/transactions/C_chain/evm_import.rs, rust/apps/avalanche/src/transactions/import.rs, rust/apps/avalanche/src/transactions/structs.rs, rust/rust_c/src/avalanche/mod.rs, rust/rust_c/src/avalanche/structs.rs, src/ui/gui_chain/multi/web3/gui_avax.c
=> fix avax bugs

src/tasks/ui_display_task.c, src/webusb_protocol/services/service_file_trans.c
=> fix nft display error

src/ui/gui_widgets/multi/web3/gui_general_home_widgets.c, src/ui/gui_widgets/multi/web3/gui_general_home_widgets.h
=> fix home widgets

src/ui/gui_widgets/gui_wallet_tutorial_widgets.c
=> update wander tutorial title

tools/padding_bin_file/padding_bin_file.py
=> disable boot padding

tools/padding_bin_file/padding_bin_file.py
Re-enable padding signature file generation in binary padding tool
=> Re-enable padding signature file generation in binary padding tool

tools/padding_bin_file/padding_bin_file.py
=> update padding script

tools/code/firmware-checker/src/error.rs, tools/code/firmware-checker/src/main.rs, tools/ota_file_maker/make_ota_file.bat
Enhance firmware checker with improved file extraction and verification
=> Enhance firmware checker with improved file extraction and verification

tools/padding_bin_file/padding_bin_file.py
Check file  exists before processing
=> Check file  exists before processing

build.py
Check file exists before processing
=> Check file exists before processing

src/webusb_protocol/services/service_device_info.c
=> fix device info

src/ui/gui_views/gui_init_view.c, src/webusb_protocol/services/service_device_info.c
=> revert device info code

src/ui/gui_widgets/setting/gui_setting_widgets.c
disable boot version on setting view
=> disable boot version on setting view

src/config/version.c, src/webusb_protocol/services/service_device_info.c
update get cypherpunk verion name
=> update get cypherpunk verion name

src/config/version.c
=> fix version

src/crypto/account_public_info.c, src/managers/keystore.c, src/ui/gui_widgets/multi/cypherpunk/gui_cypherpunk_home_widgets.c
Reverts KeystoneHQ/keystone3-firmware#1615
=> Revert "support zcash passphrase"

src/config/version.c
Update version display for different build configurations
=> Update version display for different build configurations

tools/code/firmware-checker/Cargo.lock, tools/code/firmware-checker/Cargo.toml, tools/code/firmware-checker/src/error.rs, tools/code/firmware-checker/src/main.rs
=> update firmware checker tools

src/ui/gui_widgets/gui_system_setting_widgets.c
fix system setting view scroll
=> fix system setting view scroll

rust/Cargo.lock, src/ui/gui_wallet/multi/cypherpunk/gui_wallet.h, src/ui/gui_wallet/multi/web3/gui_wallet.c, src/ui/gui_wallet/multi/web3/gui_wallet.h, src/ui/gui_widgets/multi/web3/gui_connect_wallet_widgets.c
refactor: rename ArConnect to Wander in web3 wallet functions
=> refactor: rename ArConnect to Wander in web3 wallet functions

src/ui/gui_chain/gui_chain.c, src/ui/gui_chain/gui_chain.h, src/ui/gui_components/gui_status_bar.c, src/ui/gui_widgets/multi/web3/gui_connect_wallet_widgets.c, src/ui/gui_widgets/multi/web3/gui_multi_path_coin_receive_widgets.c
fix: remove avax and core wallet
=> fix: remove avax and core wallet

src/ui/gui_widgets/multi/web3/gui_general_home_widgets.c, src/ui/gui_widgets/multi/web3/gui_general_home_widgets.h
=> fix: remove avax coin

src/ui/gui_widgets/multi/web3/gui_general_home_widgets.c, src/ui/gui_widgets/multi/web3/gui_general_home_widgets.h
Reverts KeystoneHQ/keystone3-firmware#1635
=> Revert "fix: remove avax coin"

src/ui/gui_widgets/multi/web3/gui_general_home_widgets.c, src/ui/gui_widgets/multi/web3/gui_general_home_widgets.h, src/ui/gui_widgets/multi/web3/gui_multi_path_coin_receive_widgets.c
=> remove avax coin

src/ui/gui_chain/gui_chain.c
=> fix usb transaction view after sign

src/ui/gui_widgets/multi/web3/gui_connect_wallet_widgets.c, src/ui/gui_widgets/multi/web3/gui_general_home_widgets.c
1. remove zashi wallet
2. fix ar ui bug
=> remove zashi wallet

src/crypto/account_public_info.c
Modified first receive handling in account public info
=> Modified first receive handling in account public info

src/ui/gui_widgets/multi/gui_key_derivation_request_widgets.c
Fix key derivation path widget event handling
=> Fix key derivation path widget event handling

src/ui/gui_chain/gui_btc.c
Add derivation paths for Litecoin, Dash, and Bitcoin Cash
=> Add derivation paths for Litecoin, Dash, and Bitcoin Cash

CHANGELOG-ZH.md, CHANGELOG.md
=> add 2.0.2 changelog

build.py
=> chore: update ci

src/boot_update.c
=> boot update fix

tools/padding_bin_file/padding_bin_file.py
=> fix padding script

external/mh1903_lib/MHSCPU_Driver/src/mhscpu_qspi.c, rust/apps/bitcoin/src/multi_sig/wallet.rs, rust/apps/bitcoin/src/transactions/legacy/tx_data.rs, rust/apps/bitcoin/src/transactions/psbt/wrapped_psbt.rs, src/boot_update.c, src/config/version.c, src/config/version.h, src/crypto/account_public_info.c, src/driver/drv_qspi_flash.c, src/tasks/fetch_sensitive_data_task.c, src/ui/gui_model/gui_model.c, tools/ota_file_maker/make_ota_file.bat, ui_simulator/main.c
=> 1. disable qspi code dev mode

src/ui/gui_widgets/multi/web3/gui_general_home_widgets.c, src/ui/gui_widgets/multi/web3/gui_general_home_widgets.h, src/ui/gui_widgets/multi/web3/gui_multi_path_coin_receive_widgets.c
Reverts KeystoneHQ/keystone3-firmware#1639
=> Revert "remove avax coin"

src/ui/gui_widgets/multi/web3/gui_general_home_widgets.c, src/ui/gui_widgets/multi/web3/gui_general_home_widgets.h, src/ui/gui_widgets/multi/web3/gui_multi_path_coin_receive_widgets.c
Reverts KeystoneHQ/keystone3-firmware#1680
=> Revert "Revert "remove avax coin""

external/circular_buffer/circular_buffer.c, src/ui/gui_chain/multi/cypherpunk/gui_zcash.c, src/ui/gui_chain/multi/web3/gui_sol.c
=> Refactor memory allocation in circular buffer and GUI components to use SRAM_MALLOC and SRAM_FREE for improved memory management

src/ui/gui_widgets/multi/gui_key_derivation_request_widgets.c, src/webusb_protocol/general/eapdu_services/service_resolve_ur.c
Initialize pointers to NULL and free memory in key derivation request handling
=> Initialize pointers to NULL and free memory in key derivation request handling

rust/apps/cosmos/src/transaction/utils.rs
=> fix: fix chain name

rust/apps/cosmos/src/transaction/utils.rs
=> fix: fix fake chain id

src/ui/gui_widgets/multi/gui_key_derivation_request_widgets.c, src/webusb_protocol/general/eapdu_services/service_resolve_ur.c
=> fix usb crash

CHANGELOG-ZH.md, CHANGELOG.md
=> add 2.0.6 changelog

src/ui/gui_widgets/multi/gui_key_derivation_request_widgets.c
fix close screen crash when generate ada qrcods
=> fix: fix close screen

external/FreeRTOS/FreeRTOSConfig.h, src/msg/general_msg.c, src/tasks/background_task.c, src/tasks/data_parser_task.c, src/tasks/fetch_sensitive_data_task.c, src/tasks/log_task.c
=> adjust tasks heap

external/FreeRTOS/FreeRTOSConfig.h
=> adjust total heap size

rust/rust_c/src/avalanche/mod.rs, src/ui/gui_widgets/multi/web3/gui_general_home_widgets.h
fix c chain export address display
=> fix c chain export address display

rust/rust_c/src/avalanche/mod.rs
fix avax x/p chain import c-chain transaction
=> fix avax x/p chain import c-chain transaction

src/ui/gui_chain/multi/web3/gui_avax.c, src/ui/gui_widgets/multi/web3/gui_general_home_widgets.c
=> fix avax ui bugs

rust/apps/avalanche/src/transactions/C_chain/evm_import.rs
fix avax c chain import address encode
=> fix avax c chain import address encode

rust/apps/avalanche/src/transactions/P_chain/add_permissionless_validator.rs
=> fix reward address

rust/rust_c/src/avalanche/mod.rs, src/ui/gui_chain/multi/web3/gui_avax.c
=> hide import tx path

rust/Cargo.lock, rust/apps/zcash/src/lib.rs, rust/keystore/src/algorithms/zcash/mod.rs, rust/zcash_vendor/Cargo.toml
Bumping to latest Zcash dependencies.
=> Migrate to `zcash_keys 0.8`

src/ui/gui_chain/multi/web3/gui_eth.c
=> feat: add WETH.e contract to ERC20 contracts list

src/ui/gui_widgets/multi/web3/gui_eth_batch_tx_widgets.c
=> fix ui issues

src/ui/gui_analyze/gui_resolve_ur.c, src/ui/gui_chain/multi/web3/gui_trx.c, ui_simulator/simulator_model.h
=> fix(swap): transaction parse issue

src/ui/gui_widgets/multi/web3/gui_eth_batch_tx_widgets.c
=> fix(swap): fingerprint container was not cleaned

rust/Cargo.lock, rust/Cargo.toml
=> chore: update dependency

firmware.cmake, src/ui/gui_analyze/gui_analyze.c
=> fix double display

src/ui/gui_analyze/gui_analyze.c, src/ui/gui_chain/multi/web3/gui_eth.c
=> fix  ui bugs

src/webusb_protocol/services/service_file_trans.c
=> fix laster packet data bug

src/ui/gui_analyze/gui_analyze.c, src/ui/gui_analyze/multi/web3/gui_general_analyze.h
=> fix ui analyze bugs

src/ui/gui_chain/multi/web3/gui_eth.c
=> fix uniswap crash

rust/apps/ethereum/src/swap.rs
=> fix(swap): swapkit memo issue

src/ui/gui_analyze/gui_analyze.c
=> fix eth analyze tabs

.github/workflows/on-release.yml
=> chore: add on release github hook

rust/apps/ethereum/src/swap.rs
=> feat: add xrp shortcode to erc20 swap

src/ui/gui_wallet/multi/web3/gui_wallet.c
=> fix connect wallet bug

src/ui/gui_model/gui_model.c
=> fix scan ui bug

src/ui/gui_chain/multi/web3/gui_eth.c
=> fix raw data wake up

src/ui/gui_widgets/gui_about_info_widgets.c
=> modified device info

docs/SIMULATOR.md
One step in the SIMULATOR.md for reading QR codes from a file was missing and another one was not really clear, as it only mentioned btc.
Also fixed a typo.
=> Update SIMULATOR.md steps for reading QR code data from file

src/tasks/fetch_sensitive_data_task.c
=> fix ada crash

src/ui/gui_components/gui_status_bar.c, src/ui/gui_widgets/gui_wallet_tutorial_widgets.c, src/ui/gui_widgets/multi/web3/gui_connect_wallet_widgets.c
=> iota wallet ui bugs

src/ui/gui_assets/abi/abi_ethereum.c, src/ui/gui_widgets/multi/web3/gui_eth_batch_tx_widgets.c
=> feat: add bsc thorchain contracts
