KeystoneHQ/keystone3-firmware

src/ui/gui_widgets/gui_about_info_widgets.c

Upsliding causes the interface to move up
Clicking the checksum action slides the screen to the top
about info page Swipe up and click checksum

Upsliding causes the interface to move up

---

rust/rust_c/src/common/src/macros.rs
src/ui/gui_views/gui_standard_receive_view.c

This PR fixes an issue about memory info was print without debugmemory build option, and removes an useless printf.
1. add compile config.
2. remove a printf

Fix debugmemory issues

---

src/firmware/firmware_update.c
src/ui/gui_widgets/gui_firmware_update_widgets.c

PRAD-3979
When the firmware version in the SD card <= device firmware version, the version number is not shown next to the Checksum
When the version number in the sd card is less than the current version number, the version number is also displayed

fix:checksum sdcard version show when sdcard bin version less than or equal to the current version

---

src/ui/gui_components/gui_status_bar.c
src/ui/gui_views/gui_multi_account_receive_view copy.c
src/ui/gui_views/gui_multi_path_coin_receive_view.c
src/ui/gui_views/gui_standard_receive_view.c
src/ui/gui_views/gui_utxo_receive_view.c
src/ui/gui_widgets/gui_multi_accounts_receive_widgets.c
src/ui/gui_widgets/gui_multi_path_coin_receive_widgets.c
src/ui/gui_widgets/gui_standard_receive_widgets.c
src/ui/gui_widgets/gui_utxo_receive_widgets.c

jira:PRAD-3986
After the lock screen of the switch account page is locked, the Back to Previous page button of the page address page can not be clicked
check account index after lock screen

fix switch account bug

---

src/ui/gui_model/gui_model.c

Fix the bug that entropy duplication check does not triggered.

fix(dice-rolls): check slip39 duplication

---

src/crypto/slip39/slip39.c

This PR fixes a bug caused by dice rolls changes.

fix(slip39): should not modify ems when get ms

---

src/crypto/account_public_info.c

XPUB chain number check. Regenerate XPUBs if the chain number does not match.
Upgrading firmware from each other between versions GENERAL and BTC_ONLY. The XPUB should be regenerated.

XPUB chain number check

---

src/driver/drv_battery.c

Set BATTERY_DIFF_THRESHOLD to 40

Set BATTERY_DIFF_THRESHOLD to 40

---

rust/apps/bitcoin/src/transactions/parsed_tx.rs

THIS PR fixes the bug that bitcoin transaction overview from addresses are not correctly deduplicated.

fix: bitcoin overview from addresses not correctly deduplicated

---

src/ui/gui_widgets/btc_only/gui_btc_wallet_profile_widgets.c

Close test-net checkbox after selected.
Test-net selection.

fix:close test-net checkbox after selected.

---

src/tasks/cmd_task.c

fix:exclude "test_cmd.h" when build production
build production

fix:exclude "test_cmd.h" when build production

---

src/ui/gui_views/gui_init_view.c

fix:ensure USB state before open USB connection msg box.
update firmware through SD card when usb connection established.

fix:ensure USB state before open USB connection msg box.

---

src/ui/gui_analyze/gui_analyze.c

fix:enable SwitchHidden function for BTC_ONLY.

fix:enable SwitchHidden function for BTC_ONLY.

---

src/ui/gui_components/gui_letter_tree.c

fix:memory corruption.
Input "case" or "card" on mnemonic keyboard for firmware compiled by arm-none-eabi-gcc 12.2.0.

fix:memory corruption.

---

src/ui/gui_widgets/gui_firmware_update_widgets.c

fix:delete password keyboard when update fails.

fix:delete password keyboard when update fails.

---

build.py
src/ui/gui_widgets/gui_export_pubkey_widgets.c
src/ui/gui_widgets/setting/gui_setting_widgets.c

fix: simulator build and taproot path order in btc-only testnet mode

---

src/tasks/background_task.c

fix: fix cardano withdraw qr decode crash

fix: fix cardano withdraw qr decode crash

---

src/ui/gui_widgets/gui_forget_pass_widgets.c

fix:forget password pop-up window still exists when unlock device

fix:forget password pop-up window still exists when unlock device

---

rust/apps/ethereum/src/legacy_transaction.rs

convert memo string to hex string

fix: convert memo string to hex string

---

rust/rust_c/src/arweave/src/lib.rs

fix: handle invalid primes in aes256_decrypt_primes function

---

rust/Cargo.lock
rust/Cargo.toml
rust/apps/zcash/Cargo.toml
rust/apps/zcash/src/lib.rs
rust/apps/zcash/src/pczt/sign.rs
rust/keystore/Cargo.toml
rust/keystore/src/algorithms/zcash/mod.rs
rust/rust_c/Cargo.toml
rust/rust_c/src/bindings.rs
rust/rust_c/src/lib.rs
rust/rust_c/src/trng.rs
rust/rust_c/src/zcash/src/lib.rs
src/ui/gui_chain/others/gui_zcash.c

This enables Rust crates that depend on the `getrandom` crate (either directly or via `rand::rngs::OsRng`) to get secure randomness directly instead of needing it to be passed through a per-callsite C FFI.

feat: Use TRNG as a custom `getrandom` backend

---

rust/apps/zcash/src/lib.rs
rust/apps/zcash/src/pczt/parse.rs
rust/apps/zcash/src/pczt/sign.rs
rust/keystore/src/algorithms/zcash/mod.rs
rust/zcash_vendor/src/pczt_ext.rs

The unsigned PCZT provided by the wallet contains various optional fields that we use to both check the PCZT effects and create the signatures. However, we can assume that the wallet can recover these fields if it needs them, and clear them from the PCZT we return. This should make the animated QR code displayed by the Keystone device smaller and easier to scan.
- Create a Keystone transaction in Zashi.
- Scan the Zashi animated QR code with Keystone.
- Approve the transaction in Keystone.
- Scan the Keystone animated QR code with Zashi.
- Check that the signed transaction completes and is successfully broadcast to the Zcash network.

zcash: Reduce size of the signed PCZT before returning it

---

rust/apps/cardano/src/structs.rs

fix: revert hash paired

---

rust/CMakeLists.txt

Previously compilations would fail as the toolchain wasn't properly setup. Now the firmware builds.
Unable to build as it was using the wrong toolchain
How to execute unit tests?
I setup a new Linux install
Followed the instructions in README.md
Failed at `python build.py` before the patch, now it works

./rust/CMakeLists.txt requested an older nightly build than expected
